name: SvelteKit CI/CD

on:
  push:
    branches:
      - main
      - develop

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'  # Or your desired Node.js version

      - name: Install dependencies
        run: npm install
      
      - name: Setup Playwright
        run: npx playwright install

      - name: Build SvelteKit app
        run: npm run build

      - name: Run tests (if applicable)
        run: npm run test  # Adjust if your test command is different

  # Add deployment steps if needed (e.g., to Netlify, Vercel, etc.)

